const translations = {
    "ad": "",
    "af": "off",
    "aldrig": "never",
    "alene": "alone/only",
    "alle": "all",
    "alle mennesker": "everybody/everyone",
    "allerhøjeste": "highest",
    "allerkæreste": "enchanting",
    "allernådigst": "graciously",
    "alt": "everything",
    "altid": "always",
    "altså": "so",
    "an": "on",
    "anden": "other",
    "andre": "others",
    "arbejde": "work",
    "arbejdede": "worked/working",
    "arm": "almost",
    "arrivere": "happen to",
    "at": "that",
    "bad": "begged",
    "bange": "afraid",
    "bar": "",
    "barn": "child",
    "barnet": "the child",
    "bedragere": "swindlers",
    "bedragerne": "swindlers",
    "bedre": "better",
    "bedst": "best",
    "begge": "both",
    "begynde": "begin/began",
    "begærlige": "impatient",
    "behage": "please",
    "behager": "pleases",
    "behøvede": "needed",
    "benklæderne": "trousers",
    "betragtede": "looked",
    "bifald": "approval",
    "blev": "becoming",
    "blive": "being",
    "boede": "lived",
    "briller": "glasses",
    "bruge": "use",
    "brød": "care",
    "byen": "town",
    "bære": "carry",
    "bæres": "carry",
    "da": "",
    "dag": "day",
    "dagen": "day",
    "de": "they",
    "dejlige": "lovely",
    "dejligste": "loveliest",
    "dejligt": "lovely",
    "dem": "them",
    "den": "the",
    "der": "there",
    "deres": "your/their",
    "derhen": "there",
    "dermed": "therewith",
    "det": "it/the",
    "dette": "this",
    "disse": "these",
    "dog": "",
    "dragt": "outfit",
    "drejede": "spun",
    "du": "you",
    "duede": "deserve",
    "duet": "deserve",
    "dum": "stupid",
    "dumme": "stupid",
    "dur": "deserve",
    "dyden": "beauty",
    "dårlig": "bad",
    "efter": "after",
    "egen": "own",
    "egenskab": "way",
    "egne": "own",
    "ej": "",
    "eller": "or",
    "embede": "office/posts",
    "embedsmand": "official",
    "embedsmænd": "officials",
    "en": "a/an/one",
    "end": "than",
    "endnu": "",
    "ene": "a/an/one",
    "engang": "once",
    "er": "are/am/is",
    "et": "a/an/one",
    "ethvert": "any",
    "excellent": "excellent",
    "faderen": "father",
    "famlede": "fumbled",
    "farver": "colours",
    "farverne": "colours",
    "fik": "",
    "fineste": "finest",
    "flere": "more",
    "folk": "folk",
    "folket": "crowd",
    "for": "for",
    "foran": "front",
    "forestod": "take place",
    "forfærdeligt": "terrible",
    "forklarede": "explained",
    "forlangte": "demanded",
    "formiddag": "morning",
    "fornemste": "noblest",
    "fornøjede": "delighted",
    "fornøjeligt": "splendid",
    "fornøjer": "delights",
    "forsikrede": "assured",
    "forstand": "intelligent",
    "forstod": "understood",
    "fortæller": "tell",
    "forunderlig": "peculiar",
    "forunderlige": "wonderful",
    "fra": "from",
    "fremmede": "strangers",
    "få": "getting",
    "færdige": "finished",
    "færdigt": "finished",
    "følget": "retinue",
    "før": "before",
    "først": "first",
    "første": "first",
    "gad": "would like",
    "gaden": "streets",
    "gamle": "old",
    "gang": "time",
    "ganske": "completely/most",
    "garderoben": "dressing room",
    "gav": "give",
    "gav sig ud": "pretended",
    "gik": "went",
    "give": "give",
    "gjorde": "did",
    "gjort": "done",
    "glæde": "joy",
    "god": "kind",
    "gode": "good",
    "godt": "good",
    "godt efter": "closely",
    "gud": "god",
    "gudbevares": "heaven help me",
    "guld": "gold",
    "gulvet": "floor",
    "går": "go",
    "ham": "him",
    "han": "he",
    "hans": "their",
    "har": "has/have",
    "havde": "had",
    "have dem på": "wore them",
    "hel": "whole",
    "hele": "whole",
    "hen": "there",
    "her": "here",
    "herhenne": "here",
    "herregud": "good lord",
    "hjem": "home",
    "hjertet": "heart",
    "holde": "hold",
    "holdt": "hold/holding",
    "hvad": "what",
    "hver": "every",
    "hvert": "every",
    "hvilke": "which/what/whom",
    "hvilken": "what",
    "hvilket": "what",
    "hviskede": "whispered",
    "hvor": "where",
    "hvorledes": "how",
    "hånden": "hands",
    "hænderne": "hands",
    "hænge": "wear",
    "hør": "hear",
    "hørte": "listened",
    "i": "in",
    "igen": "again",
    "igennem": "through",
    "ikke": "not",
    "ind": "into",
    "inderligt": "sincerely",
    "ingen ting": "nothing",
    "ingen mennesker": "not a person",
    "ingenting": "nothing",
    "intet": "nothing",
    "ja": "yes",
    "jeg": "i",
    "jo": "ever",
    "just": "just",
    "kammerherrerne": "noblemen",
    "kan": "can",
    "kappen": "coat",
    "kavalerer": "cavaliers",
    "kavalererne": "cavaliers",
    "kejser": "emperor",
    "kejseren": "emperor",
    "kejserens": "emperors",
    "kejserlige": "imperial",
    "kende": "tell",
    "kjole": "gown",
    "kjolen": "gown",
    "klippede": "clip",
    "kloge": "wise",
    "klæder": "clothes",
    "klæderne": "clothes",
    "knaphullet": "buttonhole",
    "kom": "came",
    "komedie": "comedy",
    "komme efter": "discover",
    "konge": "king",
    "kostbar": "precious",
    "kraft": "power",
    "kroppen": "body",
    "kræfter": "powers",
    "krøb": "shivered",
    "kulører": "colours",
    "kunne": "could/would",
    "køre": "ride",
    "lade": "let",
    "lagde": "took off",
    "langt": "far",
    "let": "light",
    "levede": "lived",
    "lidt": "slightly",
    "ligesom": "just like",
    "lille": "little",
    "listige": "crafty",
    "lod": "pretended",
    "lommer": "pockets",
    "luften": "air",
    "lykke": "success",
    "lys": "candles",
    "løftede": "lifted",
    "løjerligt": "strange",
    "mageløse": "unique",
    "magnifik": "magnificent",
    "majestæt": "majesty",
    "man": "man/one/they",
    "manden": "anyone",
    "mange": "many",
    "med": "with",
    "medens": "while",
    "meget": "very",
    "mellem": "among",
    "men": "but",
    "menneske": "person",
    "mere": "more",
    "mig": "me",
    "min": "my",
    "mindste": "slightest",
    "minister": "minister",
    "mit": "my",
    "mund": "mouth",
    "må": "may/must",
    "mænd": "men",
    "mærke med": "find out/confess",
    "mønster": "pattern",
    "mønstret": "pattern/patterns",
    "nabo": "neighbour",
    "natten": "night",
    "navn": "name",
    "nej": "no",
    "nikkede": "advised",
    "nogen": "someone",
    "noget": "anything",
    "nogle": "some",
    "nok": "",
    "nu": "now",
    "nydeligt": "pretty",
    "nye": "new",
    "nysseligt": "unsurpassed",
    "nå": "well",
    "når": "when",
    "nærmere": "nearer",
    "nævnede": "name",
    "og": "and",
    "også": "also",
    "oh": "oh",
    "om": "about/around/if/whether",
    "op": "up",
    "oppe": "up",
    "ordentligt": "properly",
    "os": "us",
    "over": "over/more than",
    "overceremonimesteren": "minister of public processions",
    "passede": "fit",
    "passer": "fit",
    "pegede": "pointed",
    "penge": "money",
    "pose": "bags",
    "procession": "procession",
    "processionen": "procession",
    "prægtige": "gorgeous",
    "prægtigste": "prettiest",
    "puttede": "popped",
    "pyntet": "well dressed",
    "på": "on",
    "rask": "",
    "ret": "",
    "ridderkors": "knights cross",
    "rige": "empire",
    "roste": "praised",
    "råbte": "cried out",
    "rådede": "advised",
    "rådet": "council",
    "røst": "prattle",
    "sad": "sat",
    "sagde": "said",
    "sakse": "scissors",
    "salen": "room",
    "samme": "same",
    "sammen": "together",
    "satte": "set",
    "se": "see",
    "seksten": "sixteen",
    "selv": "himself",
    "sende": "send",
    "sendte": "sent",
    "ser": "see",
    "sidder": "fit",
    "siden": "ago",
    "sidst": "last",
    "sige": "tell",
    "siger": "saying",
    "silke": "silk",
    "sin": "his",
    "sine": "his",
    "sit": "their/his",
    "skal": "shall",
    "skare": "troop",
    "skikkelig": "honest",
    "skikkelige": "honest",
    "skoven": "woods",
    "skrækkeligste": "worst",
    "skulle": "should/could",
    "skønne": "beautiful",
    "slet": "at all",
    "slæb": "train",
    "slæbet": "train",
    "smukke": "beautiful",
    "smukt": "beautiful",
    "snart": "soon",
    "soldater": "soldiers",
    "som": "who/which/as",
    "spejl": "mirror",
    "spejlet": "mirror",
    "spile": "flew",
    "spilede": "flew",
    "spindelvæv": "spider web",
    "spurgte": "asked",
    "stad": "city",
    "stads": "interest",
    "stak": "stacked",
    "stakkels": "poor",
    "stand": "ready",
    "stod": "going",
    "store": "big",
    "straks": "immediately",
    "stykke": "piece",
    "står": "waiting",
    "syede": "sewed",
    "syet": "sewn",
    "syntes": "suspected",
    "synål": "needles",
    "så": "so",
    "sådan": "such",
    "således": "so",
    "sælsomme": "strange",
    "særdeles": "extremely",
    "tage": "take",
    "tager": "",
    "talte": "talking",
    "thi": "as/for",
    "til": "for/at/to",
    "tilfreds": "satisfied",
    "time": "hour",
    "titel": "title",
    "to": "two",
    "tog": "take",
    "tomme": "empty",
    "travlt": "busy",
    "tro": "think",
    "troede": "believe",
    "troet": "believed",
    "tronhimlen": "canopy",
    "tronhimmel": "canopy",
    "tråd": "thread",
    "træde": "come",
    "trævl": "thread/shred",
    "turde": "dared",
    "tændt": "burned",
    "tænke": "imagine/remember",
    "tænkte": "thought",
    "tøj": "cloth",
    "tøjet": "cloth",
    "ud": "out",
    "uden": "out/without",
    "udenfor": "outside",
    "udsøgte": "chosen",
    "uhyre": "exceedingly",
    "under": "under",
    "underlig": "uncomfortable",
    "uskyldiges": "innocent",
    "usynlige": "invisible",
    "usædvanligt": "unusually",
    "utilladelig": "inexcusably",
    "var": "would/were/was",
    "ved": "at",
    "vejret": "air",
    "velsignet": "heavenly",
    "vendte": "turned",
    "vi": "we",
    "vide": "know",
    "videre fort": "so on",
    "vidste": "knew",
    "vidt": "far",
    "vil": "will",
    "ville": "wanted/would/rather",
    "vinduerne": "windows",
    "vise": "show",
    "viste": "showed",
    "vistnok": "",
    "væk": "bags",
    "være": "be",
    "været": "been/be",
    "væv": "looms",
    "væve": "weave/looms",
    "vævede": "weaving",
    "vævejunkere": "sir weaver",
    "væven": "looms",
    "vævere": "weavers",
    "væverne": "weavers",
    "væves": "woven",
    "vævestole": "looms",
    "vævning": "weaving",
    "vævningen": "weaving",
    "år": "years",
    "ærlige": "honest",
    "øjnene": "eyes"
}

const selectWordsMatcherHelper = (words, matchesSoFar) => {
  if (words.length === 0) {
    return matchesSoFar;
  } else {
    let word = words.shift();
    if (matchesSoFar === null) {
      let matchesSoFar = [
        ...document.querySelectorAll("."+word)
      ].map((item) => [item]);
      return selectWordsMatcherHelper(words, matchesSoFar);
    } else if (matchesSoFar.length === 0) {
      return []
    } else {
      matchesSoFar = matchesSoFar.map((matches) => {
        let match = matches.at(-1);
        if (match.nextElementSibling?.className.split(" ").includes(word)) {
          return [...matches, match.nextElementSibling];
        }
        return [];
      }).filter((matches) => matches.length > 0);
      return selectWordsMatcherHelper(words, matchesSoFar);
    }
  }
}

const selectWordsMatcher = (words) => {
  return selectWordsMatcherHelper(words, null);
}

const highlightElems = (elems, key) => {
  elems.forEach((match) => {
    if (match.parentElement.className.includes("t1")) {
      match.onmouseover = ((e) => {
        match.className = match.className + " highlighted";
        translations[key].split("/").forEach((word) => {
          if (word !== "") {
            if (!word.includes(" ")) {
              document.querySelectorAll("."+word).forEach((item) => {
                if (item.parentElement.className.includes("t2")) {
                  item.className = item.className + " highlighted";
                }
              });
            } else {
              let words = word.split(" ");
              let sequenceMatches = selectWordsMatcher(words);
              sequenceMatches.forEach((sequence) => {
                sequence.forEach((item) => {
                  item.className = item.className + " highlighted";
                })
              })
            }
          }
        });
      });
      match.onmouseout = ((e) => {
        match.className = match.className.replace(" highlighted", "");
        translations[key].split("/").forEach((word) => {
          if (word !== "") {
            if (!word.includes(" ")) {
              document.querySelectorAll("."+word).forEach((item) => {
                if (item.parentElement.className.includes("t2")) {
                  item.className = item.className.replace(" highlighted", "");
                }
              });
            } else {
              let words = word.split(" ");
              let sequenceMatches = selectWordsMatcher(words);
              sequenceMatches.forEach((sequence) => {
                sequence.forEach((item) => {
                  item.className = item.className.replace(" highlighted", "");
                })
              })
            }
          }
        });
      });
    }
  });
}

window.addEventListener('load', function () {
  Object.keys(translations)
    .sort((a, b) => a.length > b.length)
    .forEach((key) => {
      let danishElems = []
      if (!key.includes(" ")) {
        danishElems = document.querySelectorAll("."+key);
      } else {
        let words = key.split(" ");
        danishElems = selectWordsMatcher(words).flat();
      }
      highlightElems(danishElems, key);
    });
});
